# Generated by Django 2.2.3 on 2019-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='account/images')),
                ('livein', models.CharField(default='', max_length=200)),
                ('nick_name', models.CharField(default='', max_length=200)),
                ('work', models.CharField(default='', max_length=200)),
                ('dob', models.DateField(default='')),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
