# Generated by Django 2.2.3 on 2019-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
