# Generated by Django 2.2.3 on 2019-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190906_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.FileField(default='profile.png', upload_to='account/images'),
        ),
    ]
