# Generated by Django 2.2.7 on 2019-11-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190907_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
